In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.randn(3, 4, 5)
a

tensor([[[ 0.0194,  1.4037, -1.0438, -0.1924,  0.5489],
         [-1.3583,  1.1282, -0.5281,  0.2512, -1.0764],
         [ 0.4958, -0.2520, -0.2127,  0.5397,  2.4413],
         [-0.6149, -1.1526,  0.6924, -1.6459, -0.0467]],

        [[-0.7774,  0.0639,  1.2852, -0.7496,  0.6544],
         [-0.0161,  0.2484, -0.1432, -0.8984,  1.2495],
         [ 0.9103, -0.3682,  1.3181,  1.3190,  0.3465],
         [-0.5249, -0.9287,  0.0789,  0.6168,  0.0625]],

        [[-0.7227,  0.2368, -0.7096, -0.6570,  2.2302],
         [ 0.8977, -0.4150, -1.6656, -0.9051,  1.4166],
         [ 0.9852,  0.2197, -0.1078,  1.9827, -1.5374],
         [ 0.2609,  0.0521,  1.5684, -0.2272, -0.8682]]])

In [4]:
# 2. Выведите его форму (shape)

In [5]:
a.shape

torch.Size([3, 4, 5])

In [6]:
# 3. Приведите его к форме 6х10

In [7]:
a = a.reshape(6, 10)
a

tensor([[ 0.0194,  1.4037, -1.0438, -0.1924,  0.5489, -1.3583,  1.1282, -0.5281,
          0.2512, -1.0764],
        [ 0.4958, -0.2520, -0.2127,  0.5397,  2.4413, -0.6149, -1.1526,  0.6924,
         -1.6459, -0.0467],
        [-0.7774,  0.0639,  1.2852, -0.7496,  0.6544, -0.0161,  0.2484, -0.1432,
         -0.8984,  1.2495],
        [ 0.9103, -0.3682,  1.3181,  1.3190,  0.3465, -0.5249, -0.9287,  0.0789,
          0.6168,  0.0625],
        [-0.7227,  0.2368, -0.7096, -0.6570,  2.2302,  0.8977, -0.4150, -1.6656,
         -0.9051,  1.4166],
        [ 0.9852,  0.2197, -0.1078,  1.9827, -1.5374,  0.2609,  0.0521,  1.5684,
         -0.2272, -0.8682]])

In [8]:
a.shape

torch.Size([6, 10])

In [9]:
# 4. Создайте случайный IntTensor размера 10

In [10]:
b = torch.randint(10, size=(10,))
b

tensor([7, 9, 8, 8, 4, 4, 5, 7, 3, 2])

In [11]:
b.shape

torch.Size([10])

In [12]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [13]:
c = a * b
c

tensor([[  0.1355,  12.6332,  -8.3508,  -1.5388,   2.1954,  -5.4331,   5.6410,
          -3.6967,   0.7535,  -2.1528],
        [  3.4709,  -2.2676,  -1.7019,   4.3177,   9.7651,  -2.4595,  -5.7629,
           4.8465,  -4.9376,  -0.0934],
        [ -5.4415,   0.5755,  10.2818,  -5.9967,   2.6177,  -0.0643,   1.2420,
          -1.0022,  -2.6951,   2.4990],
        [  6.3723,  -3.3135,  10.5444,  10.5520,   1.3861,  -2.0997,  -4.6435,
           0.5523,   1.8504,   0.1249],
        [ -5.0589,   2.1308,  -5.6764,  -5.2560,   8.9208,   3.5908,  -2.0749,
         -11.6593,  -2.7152,   2.8332],
        [  6.8966,   1.9771,  -0.8622,  15.8615,  -6.1495,   1.0435,   0.2604,
          10.9785,  -0.6815,  -1.7364]])

In [14]:
c.shape

torch.Size([6, 10])

In [15]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [16]:
d = c.matmul(c.T)  # просто сам на себя нельзя умножить, размерность же не совпадает
d

tensor([[ 316.7469,  -39.7518,  -60.7034, -157.9483,  105.0505,  -46.3565],
        [ -39.7518,  221.2223,  -36.8030,   96.2344,   11.4494,   82.0234],
        [ -60.7034,  -36.8030,  194.5284,    1.3254,   48.5362, -169.7174],
        [-157.9483,   96.2344,    1.3254,  305.7507, -151.2629,  188.3357],
        [ 105.0505,   11.4494,   48.5362, -151.2629,  338.0989, -291.8739],
        [ -46.3565,   82.0234, -169.7174,  188.3357, -291.8739,  466.7814]])

In [17]:
d.shape

torch.Size([6, 6])

In [18]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

$y = x^3 + z - 75t$

$y' = 3x^2 + 1 - 75 = 3x^2 - 74$

Так как z и t после диффиринцирования стали константами то в итоге подставляем в полученное уравнение только x.

$y' = 3x^2 - 74 = 3\cdot 1^2 - 74 = -71 $

Проверим с помощью torch:

In [19]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)
x, z, t

(tensor([1.], requires_grad=True),
 tensor([0.5000], requires_grad=True),
 tensor([2.], requires_grad=True))

In [20]:
y = x ** 3 + z - 75 * t

In [21]:
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [22]:
y.backward()

In [23]:
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [24]:
x.grad + z.grad + t.grad

# Вот здесь я не понял есть ли метод сразу получить производную из функции 'y' без ручного суммирования производных?

tensor([-71.])

In [25]:
# 8. Создайте единичный тензор размера 5x6

In [26]:
e = torch.zeros((5, 6)).fill_(1)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [27]:
e.shape

torch.Size([5, 6])

In [28]:
# 9. Переведите его в формат numpy

In [29]:
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)