In [1]:
import torch

In [28]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [29]:
a = torch.randn(3, 4, 5)
a

tensor([[[-1.1740e+00,  6.8816e-02, -1.7323e+00,  7.0450e-01,  5.7384e-01],
         [ 7.0294e-02, -1.4653e-01, -2.5573e+00, -1.9047e-01, -1.2566e+00],
         [-1.4219e+00,  1.2795e+00,  6.0846e-01, -3.6704e-01, -2.9733e-01],
         [ 6.9641e-02, -2.9311e-01, -3.0643e-02, -1.4989e+00, -1.1786e-03]],

        [[ 1.0695e+00, -1.5560e+00, -1.0112e+00, -8.1238e-01, -3.6146e-01],
         [ 1.6002e+00,  7.8384e-01,  3.0121e-01, -1.5495e-01,  1.3501e+00],
         [ 3.8076e-01, -1.9769e-01, -7.5509e-01,  1.1057e+00,  1.5434e+00],
         [-1.1252e+00, -4.0408e-01, -8.0672e-01,  4.9157e-01,  7.4210e-01]],

        [[-1.5776e+00, -1.6508e-01,  3.9824e-01,  9.8806e-01,  8.9964e-01],
         [-1.6428e+00,  6.0556e-01, -2.7703e+00, -1.1773e+00,  6.0762e-01],
         [-1.6303e+00, -1.2972e+00,  1.1801e+00, -1.2666e+00, -8.1126e-02],
         [ 5.0862e-01,  4.6072e-01,  6.6230e-01,  3.1414e-01,  1.4148e+00]]])

In [30]:
# 2. Выведите его форму (shape)

In [31]:
a.shape

torch.Size([3, 4, 5])

In [32]:
# 3. Приведите его к форме 6х10

In [33]:
a = a.reshape(6, 10)
a

tensor([[-1.1740e+00,  6.8816e-02, -1.7323e+00,  7.0450e-01,  5.7384e-01,
          7.0294e-02, -1.4653e-01, -2.5573e+00, -1.9047e-01, -1.2566e+00],
        [-1.4219e+00,  1.2795e+00,  6.0846e-01, -3.6704e-01, -2.9733e-01,
          6.9641e-02, -2.9311e-01, -3.0643e-02, -1.4989e+00, -1.1786e-03],
        [ 1.0695e+00, -1.5560e+00, -1.0112e+00, -8.1238e-01, -3.6146e-01,
          1.6002e+00,  7.8384e-01,  3.0121e-01, -1.5495e-01,  1.3501e+00],
        [ 3.8076e-01, -1.9769e-01, -7.5509e-01,  1.1057e+00,  1.5434e+00,
         -1.1252e+00, -4.0408e-01, -8.0672e-01,  4.9157e-01,  7.4210e-01],
        [-1.5776e+00, -1.6508e-01,  3.9824e-01,  9.8806e-01,  8.9964e-01,
         -1.6428e+00,  6.0556e-01, -2.7703e+00, -1.1773e+00,  6.0762e-01],
        [-1.6303e+00, -1.2972e+00,  1.1801e+00, -1.2666e+00, -8.1126e-02,
          5.0862e-01,  4.6072e-01,  6.6230e-01,  3.1414e-01,  1.4148e+00]])

In [34]:
a.shape

torch.Size([6, 10])

In [35]:
# 4. Создайте случайный IntTensor размера 10

In [36]:
b = torch.randint(10, size=(10,))
b

tensor([5, 7, 3, 1, 9, 7, 3, 7, 3, 3])

In [37]:
b.shape

torch.Size([10])

In [40]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [41]:
c = a * b
c

tensor([[-5.8699e+00,  4.8171e-01, -5.1968e+00,  7.0450e-01,  5.1645e+00,
          4.9206e-01, -4.3960e-01, -1.7901e+01, -5.7140e-01, -3.7697e+00],
        [-7.1097e+00,  8.9564e+00,  1.8254e+00, -3.6704e-01, -2.6759e+00,
          4.8749e-01, -8.7933e-01, -2.1450e-01, -4.4967e+00, -3.5358e-03],
        [ 5.3474e+00, -1.0892e+01, -3.0336e+00, -8.1238e-01, -3.2532e+00,
          1.1201e+01,  2.3515e+00,  2.1085e+00, -4.6485e-01,  4.0503e+00],
        [ 1.9038e+00, -1.3839e+00, -2.2653e+00,  1.1057e+00,  1.3890e+01,
         -7.8762e+00, -1.2122e+00, -5.6471e+00,  1.4747e+00,  2.2263e+00],
        [-7.8881e+00, -1.1555e+00,  1.1947e+00,  9.8806e-01,  8.0967e+00,
         -1.1499e+01,  1.8167e+00, -1.9392e+01, -3.5319e+00,  1.8229e+00],
        [-8.1516e+00, -9.0803e+00,  3.5403e+00, -1.2666e+00, -7.3013e-01,
          3.5603e+00,  1.3821e+00,  4.6361e+00,  9.4241e-01,  4.2444e+00]])

In [42]:
c.shape

torch.Size([6, 10])

In [39]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [47]:
d = c.matmul(c.T)  # просто сам на себя нельзя умножить, размерность же не совпадает
d

tensor([[ 424.2967,   29.5317,  -86.5134,  160.9591,  417.8830,  -77.9736],
        [  29.5317,  162.6685, -127.0863,  -75.8416,   38.7156,  -19.2171],
        [ -86.5134, -127.0863,  319.7358, -108.6097, -216.7597,  117.6332],
        [ 160.9591,  -75.8416, -108.6097,  307.3582,  294.1603,  -67.5736],
        [ 417.8830,   38.7156, -216.7597,  294.1603,  658.8995,  -52.0657],
        [ -77.9736,  -19.2171,  117.6332,  -67.5736,  -52.0657,  218.5534]])

In [48]:
d.shape

torch.Size([6, 6])

In [49]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [61]:
-71

-71

In [62]:
# 8. Создайте единичный тензор размера 5x6

In [52]:
e = torch.zeros((5, 6)).fill_(1)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [53]:
e.shape

torch.Size([5, 6])

In [54]:
# 9. Переведите его в формат numpy

In [60]:
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)